import { ChannelPartner } from './types';

export const CHANNEL_PARTNERS_DATABASE: ChannelPartner[] = [
  // Delhi NCR
  {
    id: 'sca-delhi-01',
    name: 'Delhi SC/ST/OBC/Minorities Dev & Fin Corp (DSFDC)',
    type: 'SCA',
    branchName: 'Headquarters & Central District Office',
    state: 'Delhi',
    district: 'Central Delhi',
    address: 'Ambedkar Bhawan, Sector 16, Rohini & Shankar Market, Connaught Place, New Delhi',
    lat: 28.6315,
    lng: 77.2167,
    phone: '+91-11-23341829',
    email: 'contact@dsfdc.delhi.gov.in',
    nodalOfficer: 'Shri R.K. Verma (General Manager - Credit)',
    supportedSchemes: ['nsfdc-mfs', 'nsfdc-msy', 'nsfdc-tls', 'nsfdc-els', 'nsfdc-gbs', 'nsfdc-lvy', 'nskfdc-srms'],
    npaRate: 2.3,
    fundAllocationRemainingPercent: 88,
    npaStatus: 'HEALTHY_ACTIVE',
    statusReason: 'Highest recovery track record with active quarterly fund disbursement of ₹8.5 Cr available.',
    turnaroundTimeDays: 12,
    rating: 4.8
  },
  {
    id: 'psb-sbi-delhi-01',
    name: 'State Bank of India (SBI) - Lead Bank & MSME Cell',
    type: 'PSB',
    branchName: 'Parliament Street SME Branch',
    state: 'Delhi',
    district: 'New Delhi',
    address: '11, Parliament Street, New Delhi, 110001',
    lat: 28.6271,
    lng: 77.2144,
    phone: '+91-11-23746401',
    email: 'sbi.00691@sbi.co.in',
    nodalOfficer: 'Ms. Sunita Meena (Lead District Officer)',
    supportedSchemes: ['nsfdc-tls', 'nsfdc-els', 'nsfdc-gbs', 'msje-vcf-sc'],
    npaRate: 3.1,
    fundAllocationRemainingPercent: 74,
    npaStatus: 'HEALTHY_ACTIVE',
    statusReason: 'Active channel partner with automated direct credit processing for Education & Term Loans.',
    turnaroundTimeDays: 14,
    rating: 4.6
  },
  {
    id: 'mfi-fusion-delhi-01',
    name: 'Fusion Micro Finance Ltd (Channel MFI)',
    type: 'NBFC_MFI',
    branchName: 'East Delhi & Shakarpur Nodal Branch',
    state: 'Delhi',
    district: 'East Delhi',
    address: 'Plot 14, Vikas Marg, Laxmi Nagar, Delhi 110092',
    lat: 28.6304,
    lng: 77.2773,
    phone: '+91-11-46646600',
    email: 'microcredit@fusionmicrofinance.com',
    nodalOfficer: 'Mr. Arvind Chauhan (Cluster Head)',
    supportedSchemes: ['nsfdc-mfs', 'nsfdc-msy', 'nsfdc-lvy'],
    npaRate: 1.8,
    fundAllocationRemainingPercent: 92,
    npaStatus: 'HEALTHY_ACTIVE',
    statusReason: 'Rapid 7-day disbursement for Women Self-Help Groups and street nano-vendors.',
    turnaroundTimeDays: 7,
    rating: 4.9
  },

  // Uttar Pradesh
  {
    id: 'sca-up-lucknow-01',
    name: 'UP SC Finance & Development Corp (UPSCFDC)',
    type: 'SCA',
    branchName: 'Nawal Kishore Road State Nodal Office',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    address: 'B-38, Kranti Marg, Nawal Kishore Road, Hazratganj, Lucknow 226001',
    lat: 26.8526,
    lng: 80.9422,
    phone: '+91-522-2621940',
    email: 'md@upscfdc.up.gov.in',
    nodalOfficer: 'Dr. Akhilesh Kumar (Nodal SCA Director)',
    supportedSchemes: ['nsfdc-mfs', 'nsfdc-msy', 'nsfdc-tls', 'nsfdc-els', 'nsfdc-gbs', 'nsfdc-lvy', 'nskfdc-srms'],
    npaRate: 2.9,
    fundAllocationRemainingPercent: 81,
    npaStatus: 'HEALTHY_ACTIVE',
    statusReason: 'Special subsidized corridor active for agricultural, sanitation, and MSME applications.',
    turnaroundTimeDays: 15,
    rating: 4.7
  },
  {
    id: 'rrb-aryavart-up-01',
    name: 'Aryavart Bank (Regional Rural Bank)',
    type: 'RRB',
    branchName: 'Alambagh Regional Credit Centre',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    address: 'A-2/46, Vijay Nagar, Alambagh, Lucknow 226005',
    lat: 26.8176,
    lng: 80.8988,
    phone: '+91-522-2457811',
    email: 'rrb.alambagh@aryavartbank.in',
    nodalOfficer: 'Shri B.P. Yadav (Chief Rural Manager)',
    supportedSchemes: ['nsfdc-mfs', 'nsfdc-msy', 'nsfdc-lvy', 'nsfdc-tls'],
    npaRate: 4.6,
    fundAllocationRemainingPercent: 28,
    npaStatus: 'QUOTA_RESTRICTED',
    statusReason: 'High application intake this quarter; new quota limited to women applicants and small farm equipment.',
    turnaroundTimeDays: 21,
    rating: 4.0
  },
  {
    id: 'psb-pnb-varanasi-01',
    name: 'Punjab National Bank - Lead District Office',
    type: 'PSB',
    branchName: 'Cantonment Varanasi Branch',
    state: 'Uttar Pradesh',
    district: 'Varanasi',
    address: 'Maldahiya Crossing, Cantonment, Varanasi 221002',
    lat: 25.3283,
    lng: 82.9866,
    phone: '+91-542-2503921',
    email: 'ldo.varanasi@pnb.co.in',
    nodalOfficer: 'Ms. Reena Tripathi (Lead Bank Manager)',
    supportedSchemes: ['nsfdc-tls', 'nsfdc-els', 'nsfdc-gbs'],
    npaRate: 8.2,
    fundAllocationRemainingPercent: 6,
    npaStatus: 'HIGH_NPA_SUSPENDED',
    statusReason: 'Disbursement temporarily halted due to elevated overdues (NPA 8.2%). Router redirects to nearest UPSCFDC / SBI.',
    turnaroundTimeDays: 35,
    rating: 2.8
  },

  // Maharashtra
  {
    id: 'sca-mpbcdc-mumbai-01',
    name: 'Mahatama Phule Backward Classes Dev Corp (MPBCDC)',
    type: 'SCA',
    branchName: 'Mumbai Suburban & HQ Office',
    state: 'Maharashtra',
    district: 'Mumbai',
    address: 'Pravasi Industrial Estate, Goregaon West / Fort, Mumbai 400062',
    lat: 19.1663,
    lng: 72.8493,
    phone: '+91-22-28723901',
    email: 'mpbcdc.mumbai@maharashtra.gov.in',
    nodalOfficer: 'Smt. Pratibha Kamble (Deputy General Manager)',
    supportedSchemes: ['nsfdc-mfs', 'nsfdc-msy', 'nsfdc-tls', 'nsfdc-els', 'nsfdc-gbs', 'nsfdc-lvy', 'nskfdc-srms'],
    npaRate: 2.4,
    fundAllocationRemainingPercent: 79,
    npaStatus: 'HEALTHY_ACTIVE',
    statusReason: 'High performance state channel partner; express verification desk active for education & startups.',
    turnaroundTimeDays: 14,
    rating: 4.8
  },
  {
    id: 'psb-bob-pune-01',
    name: 'Bank of Baroda - Specialized SME & Lead Bank',
    type: 'PSB',
    branchName: 'Shivajinagar Pune Branch',
    state: 'Maharashtra',
    district: 'Pune',
    address: 'FC Road, Near Deccan Gymkhana, Shivajinagar, Pune 411004',
    lat: 18.5204,
    lng: 73.8443,
    phone: '+91-20-25531980',
    email: 'sme.pune@bankofbaroda.com',
    nodalOfficer: 'Shri Vikram Shinde (Chief Manager - Priority Credit)',
    supportedSchemes: ['nsfdc-tls', 'nsfdc-els', 'nsfdc-gbs', 'msje-vcf-sc'],
    npaRate: 2.7,
    fundAllocationRemainingPercent: 84,
    npaStatus: 'HEALTHY_ACTIVE',
    statusReason: 'Authorized desk for green business solar plants and student abroad education finance.',
    turnaroundTimeDays: 16,
    rating: 4.7
  },
  {
    id: 'rrb-mgb-aurangabad-01',
    name: 'Maharashtra Gramin Bank (MGB)',
    type: 'RRB',
    branchName: 'Marathwada Divisional Office',
    state: 'Maharashtra',
    district: 'Chhatrapati Sambhaji Nagar',
    address: 'Shivaji Nagar, Jalna Road, Sambhaji Nagar 431005',
    lat: 19.8762,
    lng: 75.3433,
    phone: '+91-240-2485900',
    email: 'mgb.aurangabad@mahagramin.in',
    nodalOfficer: 'Mr. Santosh Deshmukh (Regional Manager)',
    supportedSchemes: ['nsfdc-mfs', 'nsfdc-msy', 'nsfdc-lvy'],
    npaRate: 3.4,
    fundAllocationRemainingPercent: 65,
    npaStatus: 'HEALTHY_ACTIVE',
    statusReason: 'Regular processing for agro-allied, poultry, and micro artisan enterprises.',
    turnaroundTimeDays: 18,
    rating: 4.4
  },

  // Bihar
  {
    id: 'sca-bihar-patna-01',
    name: 'Bihar State SC Co-operative Dev Corp (BSSCCDC)',
    type: 'SCA',
    branchName: 'Vikas Bhawan Patna',
    state: 'Bihar',
    district: 'Patna',
    address: 'Old Secretariat Campus, Bailey Road, Patna 800015',
    lat: 25.6093,
    lng: 85.1235,
    phone: '+91-612-2215891',
    email: 'md@bssccdc.bihar.gov.in',
    nodalOfficer: 'Shri Manoj Paswan (Managing Director)',
    supportedSchemes: ['nsfdc-mfs', 'nsfdc-msy', 'nsfdc-tls', 'nsfdc-els', 'nsfdc-lvy', 'nskfdc-srms'],
    npaRate: 3.2,
    fundAllocationRemainingPercent: 86,
    npaStatus: 'HEALTHY_ACTIVE',
    statusReason: 'Direct state coordination with block development officers (BDO) for faster documentation.',
    turnaroundTimeDays: 15,
    rating: 4.6
  },
  {
    id: 'psb-uboi-patna-01',
    name: 'Union Bank of India - Priority Sector Hub',
    type: 'PSB',
    branchName: 'Exhibition Road Main Branch',
    state: 'Bihar',
    district: 'Patna',
    address: 'Exhibition Road, Near Dak Bungalow, Patna 800001',
    lat: 25.6115,
    lng: 85.1384,
    phone: '+91-612-2321450',
    email: 'patna.priority@unionbankofindia.bank',
    nodalOfficer: 'Shri R.R. Sinha (Assistant General Manager)',
    supportedSchemes: ['nsfdc-tls', 'nsfdc-els', 'nsfdc-gbs'],
    npaRate: 7.8,
    fundAllocationRemainingPercent: 9,
    npaStatus: 'HIGH_NPA_SUSPENDED',
    statusReason: 'High non-performing assets ratio (7.8%). Automated router redirects applications to BSSCCDC.',
    turnaroundTimeDays: 40,
    rating: 2.9
  },

  // Karnataka
  {
    id: 'sca-karnataka-bengaluru-01',
    name: 'Dr. B.R. Ambedkar Development Corporation (KADCL)',
    type: 'SCA',
    branchName: 'Karnataka State Apex Office',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    address: '9th Floor, Vishveshwaraiah Mini Tower, Dr. Ambedkar Veedhi, Bengaluru 560001',
    lat: 12.9784,
    lng: 77.5913,
    phone: '+91-80-22867011',
    email: 'contact@adcl.karnataka.gov.in',
    nodalOfficer: 'Dr. H. Nagaraj (General Manager)',
    supportedSchemes: ['nsfdc-mfs', 'nsfdc-msy', 'nsfdc-tls', 'nsfdc-els', 'nsfdc-gbs', 'nsfdc-lvy', 'nskfdc-srms'],
    npaRate: 2.0,
    fundAllocationRemainingPercent: 90,
    npaStatus: 'HEALTHY_ACTIVE',
    statusReason: 'Seamless integration with Seva Sindhu state portal; online sanctioned disbursements.',
    turnaroundTimeDays: 10,
    rating: 4.9
  },
  {
    id: 'psb-canara-bengaluru-01',
    name: 'Canara Bank - Lead Bank & MSME Sulabh',
    type: 'PSB',
    branchName: 'Gandhinagar Regional Office',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    address: 'Circle Office, Gandhinagar, Bengaluru 560009',
    lat: 12.9767,
    lng: 77.5753,
    phone: '+91-80-22268490',
    email: 'cb.blr.msme@canarabank.com',
    nodalOfficer: 'Ms. Meenakshi S (Assistant General Manager)',
    supportedSchemes: ['nsfdc-tls', 'nsfdc-els', 'nsfdc-gbs', 'msje-vcf-sc'],
    npaRate: 2.5,
    fundAllocationRemainingPercent: 78,
    npaStatus: 'HEALTHY_ACTIVE',
    statusReason: 'Direct tie-ups with technical universities and IT incubator parks for SC entrepreneurs.',
    turnaroundTimeDays: 14,
    rating: 4.7
  },
  {
    id: 'mfi-creditaccess-bengaluru-01',
    name: 'CreditAccess Grameen Ltd (Channel Partner MFI)',
    type: 'NBFC_MFI',
    branchName: 'Peenya Micro-Enterprise Branch',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    address: '49, 46th Cross, 8th Block, Jayanagar / Peenya, Bengaluru 560082',
    lat: 13.0285,
    lng: 77.5197,
    phone: '+91-80-22637300',
    email: 'ruralcredit@cagrameen.in',
    nodalOfficer: 'Mr. Vinay Kumar (State Operations Lead)',
    supportedSchemes: ['nsfdc-mfs', 'nsfdc-msy', 'nsfdc-lvy'],
    npaRate: 1.5,
    fundAllocationRemainingPercent: 95,
    npaStatus: 'HEALTHY_ACTIVE',
    statusReason: 'Top tier recovery discipline with weekly doorstep counseling for women micro-entrepreneurs.',
    turnaroundTimeDays: 8,
    rating: 4.9
  },

  // Tamil Nadu
  {
    id: 'sca-tahdco-chennai-01',
    name: 'Tamil Nadu Adi Dravidar Housing & Dev Corp (TAHDCO)',
    type: 'SCA',
    branchName: 'Chennai District Office & State HQ',
    state: 'Tamil Nadu',
    district: 'Chennai',
    address: 'No. 31, Cenotaph Road, Teynampet, Chennai 600018',
    lat: 13.0339,
    lng: 80.2458,
    phone: '+91-44-24344407',
    email: 'tahdco@tn.gov.in',
    nodalOfficer: 'Thiru K. Senthil Kumar (District Manager)',
    supportedSchemes: ['nsfdc-mfs', 'nsfdc-msy', 'nsfdc-tls', 'nsfdc-els', 'nsfdc-gbs', 'nsfdc-lvy', 'nskfdc-srms'],
    npaRate: 2.2,
    fundAllocationRemainingPercent: 85,
    npaStatus: 'HEALTHY_ACTIVE',
    statusReason: 'Direct state capital subsidy up to 30% linked with NSFDC credit facility.',
    turnaroundTimeDays: 12,
    rating: 4.8
  },
  {
    id: 'psb-iob-chennai-01',
    name: 'Indian Overseas Bank - Central Priority Sector Cell',
    type: 'PSB',
    branchName: 'Mount Road Main Branch',
    state: 'Tamil Nadu',
    district: 'Chennai',
    address: '763 Anna Salai, Chennai 600002',
    lat: 13.0645,
    lng: 80.2673,
    phone: '+91-44-28525280',
    email: 'priority@iob.in',
    nodalOfficer: 'Ms. Malathi R (Senior Manager)',
    supportedSchemes: ['nsfdc-tls', 'nsfdc-els', 'nsfdc-gbs'],
    npaRate: 4.9,
    fundAllocationRemainingPercent: 32,
    npaStatus: 'QUOTA_RESTRICTED',
    statusReason: 'Quarterly funds utilized 68%; prioritizing education loans and green commercial vehicles.',
    turnaroundTimeDays: 22,
    rating: 4.1
  },

  // Rajasthan
  {
    id: 'sca-anuja-jaipur-01',
    name: 'Rajasthan SC/ST Fin & Dev Co-op Corp (Anuja Nigam)',
    type: 'SCA',
    branchName: 'Nehru Sahakar Bhawan Jaipur',
    state: 'Rajasthan',
    district: 'Jaipur',
    address: 'Nehru Sahakar Bhawan, 4th Floor, 22 Godam Circle, Jaipur 302005',
    lat: 26.9022,
    lng: 75.7951,
    phone: '+91-141-2740417',
    email: 'contact.anuja@rajasthan.gov.in',
    nodalOfficer: 'Shri Ramavatar Meena (Additional Director)',
    supportedSchemes: ['nsfdc-mfs', 'nsfdc-msy', 'nsfdc-tls', 'nsfdc-els', 'nsfdc-gbs', 'nsfdc-lvy', 'nskfdc-srms'],
    npaRate: 2.6,
    fundAllocationRemainingPercent: 82,
    npaStatus: 'HEALTHY_ACTIVE',
    statusReason: 'Subsidized loan sanctions for rural handicrafts, leather work, and modern transport vehicles.',
    turnaroundTimeDays: 14,
    rating: 4.7
  },

  // West Bengal
  {
    id: 'sca-wb-kolkata-01',
    name: 'West Bengal SC & ST Dev & Fin Corp (WBSCSTDFC)',
    type: 'SCA',
    branchName: 'Salt Lake Regional Directorate',
    state: 'West Bengal',
    district: 'Kolkata',
    address: 'CF-217/A-1, Sector-I, Salt Lake City, Kolkata 700064',
    lat: 22.5855,
    lng: 88.4116,
    phone: '+91-33-23340552',
    email: 'wbscstdfc@wb.gov.in',
    nodalOfficer: 'Mr. Subir Mondal (Deputy Director)',
    supportedSchemes: ['nsfdc-mfs', 'nsfdc-msy', 'nsfdc-tls', 'nsfdc-els', 'nsfdc-gbs', 'nsfdc-lvy', 'nskfdc-srms'],
    npaRate: 2.8,
    fundAllocationRemainingPercent: 80,
    npaStatus: 'HEALTHY_ACTIVE',
    statusReason: 'Active convergence with Sabuj Sathi and state MSME skill clusters.',
    turnaroundTimeDays: 16,
    rating: 4.6
  }
];
